### ISSUE TITLE
numpy ImportError after installation from source

### ISSUE THREAD

**Issue by theoschutt** [des-labs/easyaccess#2]
I am trying to install `easyaccess` on the NERSC Cori global homes filesystem (SUSE Linux Enterprise Server 15). I installed the Oracle Instant Client (instantclient-basic-linux.x64-21.3.0.0.0.zip) from [here](https://www.oracle.com/database/technologies/instant-client/linux-x86-64-downloads.html) following the instructions at the bottom of the page (through step 5). I then cloned this repo and ran the installation. The install log is attached: [ea_install.log](https://github.com/des-labs/easyaccess/files/6995735/ea_install.log). I am also attaching a list of the packages in the environment after installation: [env_packages.txt](https://github.com/des-labs/easyaccess/files/6995740/env_packages.txt).

After installation, I ran the unit tests, and almost all passed. The only failures came from (1) not having the credentials for db-desdr in `test_connection.py`, and (2) there's a python 2 style print statement in `test_load_table.py` and I don't have all the packages installed for python 2.7.

However, when I input `easyaccess` at the command line, I immediately get the following error:

```
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
Traceback (most recent call last):
  File "/global/homes/s/schutt20/miniconda3/envs/easyaccess/bin/easyaccess", line 4, in <module>
    __import__('pkg_resources').run_script('easyaccess==1.4.8.dev0', 'easyaccess')
  File "/global/homes/s/schutt20/miniconda3/envs/easyaccess/lib/python3.9/site-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/global/homes/s/schutt20/miniconda3/envs/easyaccess/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1455, in run_script
    exec(script_code, namespace, namespace)
  File "/global/u1/s/schutt20/miniconda3/envs/easyaccess/lib/python3.9/site-packages/easyaccess-1.4.8.dev0-py3.9.egg/EGG-INFO/scripts/easyaccess", line 2, in <module>
    # EASY-INSTALL-SCRIPT: 'easyaccess==1.4.8.dev0','easyaccess'
  File "<frozen zipimport>", line 259, in load_module
  File "/global/u1/s/schutt20/miniconda3/envs/easyaccess/lib/python3.9/site-packages/easyaccess-1.4.8.dev0-py3.9.egg/easyaccess/__init__.py", line 1, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/global/u1/s/schutt20/miniconda3/envs/easyaccess/lib/python3.9/site-packages/easyaccess-1.4.8.dev0-py3.9.egg/easyaccess/easyaccess.py", line 18, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/global/u1/s/schutt20/miniconda3/envs/easyaccess/lib/python3.9/site-packages/easyaccess-1.4.8.dev0-py3.9.egg/easyaccess/eautils/fileio.py", line 15, in <module>
  File "/global/u1/s/schutt20/miniconda3/envs/easyaccess/lib/python3.9/site-packages/fitsio-1.0.5-py3.9-linux-x86_64.egg/fitsio/__init__.py", line 9, in <module>
    from . import fitslib   # noqa
  File "/global/u1/s/schutt20/miniconda3/envs/easyaccess/lib/python3.9/site-packages/fitsio-1.0.5-py3.9-linux-x86_64.egg/fitsio/fitslib.py", line 27, in <module>
    from . import _fitsio_wrap
ImportError: numpy.core.multiarray failed to import
```

Any help would be appreciated. Thanks!

**Comment by theoschutt** [comment]
I had `numpy==1.20.3` installed in the environment, which conflicted with the version used in the `easyaccess` build (`numpy==1.19.2`). Manually downgrading the environment version to `numpy==1.19.2` solved the issue.
