### ISSUE TITLE
exact numpy pin

### ISSUE THREAD

**Issue by beckermr** [des-labs/easyaccess#3]
There is very little chance the exact numpy pin is needed:

```
$ easyaccess --db desoper
Traceback (most recent call last):
  File "/Users/beckermr/miniconda3/envs/desy6/lib/python3.8/site-packages/pkg_resources/__init__.py", line 573, in _build_master
    ws.require(__requires__)
  File "/Users/beckermr/miniconda3/envs/desy6/lib/python3.8/site-packages/pkg_resources/__init__.py", line 891, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Users/beckermr/miniconda3/envs/desy6/lib/python3.8/site-packages/pkg_resources/__init__.py", line 782, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (numpy 1.21.5 (/Users/beckermr/miniconda3/envs/desy6/lib/python3.8/site-packages), Requirement.parse('numpy==1.19.2'), {'easyaccess'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/beckermr/miniconda3/envs/desy6/bin/easyaccess", line 4, in <module>
    __import__('pkg_resources').require('easyaccess==1.4.8.dev0')
  File "/Users/beckermr/miniconda3/envs/desy6/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3267, in <module>
    def _initialize_master_working_set():
  File "/Users/beckermr/miniconda3/envs/desy6/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3241, in _call_aside
    f(*args, **kwargs)
  File "/Users/beckermr/miniconda3/envs/desy6/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3279, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Users/beckermr/miniconda3/envs/desy6/lib/python3.8/site-packages/pkg_resources/__init__.py", line 575, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/Users/beckermr/miniconda3/envs/desy6/lib/python3.8/site-packages/pkg_resources/__init__.py", line 588, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/Users/beckermr/miniconda3/envs/desy6/lib/python3.8/site-packages/pkg_resources/__init__.py", line 777, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'numpy==1.19.2' distribution was not found and is required by easyaccess
```

**Comment by manning-ncsa** [comment]
@beckermr What do you recommend? Changing https://github.com/des-labs/easyaccess/blob/master/setup.py#L48 to `>=`?

**Comment by beckermr** [comment]
If all you are doing are simple array manipulations, I doubt you need a pin at all. `>=` might be ok too.

**Comment by manning-ncsa** [comment]
I was not the developer of easyaccess (Matias was) so I don't have experience modifying its guts. Would you be willing to branch from [tag 1.4.8](https://github.com/des-labs/easyaccess/tree/1.4.8) and test your proposal against some use cases? I see there is a [tests directory](https://github.com/des-labs/easyaccess/tree/master/tests). Perhaps that can be used to check that nothing breaks?

**Comment by beckermr** [comment]
I won't have time to do that. I looked through all of the numpy calls and >= the current version should be fine.

**Comment by manning-ncsa** [comment]
@Michael-D-Johnson I created a new release 1.4.9 based on the compelling and rigorous arguments of @beckermr. I did at least verify that the usage of `numpy` is pretty basic. Will you please add an associated release to https://pypi.org/project/easyaccess/ at some point?

**Comment by beckermr** [comment]
I would not call my arguments compelling or rigorous. ;p

**Comment by Michael-D-Johnson** [comment]
@beckermr  In the past I've been able to workaround numpy issues by forcing an upgrade via pip on my system:
```
python -m pip install numpy --upgrade
```
It complains about not matching the easyaccess dist but I was able to load easyaccess successfully after doing that.

However, I've pushed a new version based on @manning-ncsa  tag to pypi (1.4.9) that doesn't limit numpy to an exact version. Please let us know if that works out.

**Comment by beckermr** [comment]
thank you!
